"""numarul de locuri al salii

Revision ID: 28d5f16a85fe
Revises: a040eb86e6fa
Create Date: 2026-08-04 11:41:25.503442

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28d5f16a85fe"
down_revision: Union[str, Sequence[str], None] = "a040eb86e6fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("SALA", schema=None) as batch_op:
        batch_op.add_column(sa.Column("NR_LOCURI", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("SALA", schema=None) as batch_op:
        batch_op.drop_column("NR_LOCURI")

    # ### end Alembic commands ###
