"""versiunile anterioare ale orarului

Revision ID: 9242bdc586c9
Revises: 28d5f16a85fe
Create Date: 2026-09-29 19:47:38.303592

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9242bdc586c9"
down_revision: Union[str, Sequence[str], None] = "28d5f16a85fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "VERSIUNE_ORAR",
        sa.Column("ID_VERSIUNE", sa.Integer(), nullable=False),
        sa.Column("AN_UNIV", sa.String(length=9), nullable=False),
        sa.Column("SEMESTRU", sa.Integer(), nullable=False),
        sa.Column("PUBLICAT", sa.DateTime(), nullable=True),
        sa.Column("ARHIVAT_LA", sa.DateTime(), nullable=False),
        sa.Column("NR_ORE", sa.Integer(), nullable=False),
        sa.CheckConstraint("SEMESTRU IN (1,2)", name="ck_versiune_semestru"),
        sa.PrimaryKeyConstraint("ID_VERSIUNE"),
    )
    with op.batch_alter_table("VERSIUNE_ORAR", schema=None) as batch_op:
        batch_op.create_index("ix_versiune_an_sem", ["AN_UNIV", "SEMESTRU"], unique=False)

    op.create_table(
        "ORA_ARHIVA",
        sa.Column("ID_ORA_ARHIVA", sa.Integer(), nullable=False),
        sa.Column("ID_VERSIUNE", sa.Integer(), nullable=False),
        sa.Column("ID_ORA_ORIGINALA", sa.Integer(), nullable=False),
        sa.Column("ID_PROFESOR", sa.Integer(), nullable=True),
        sa.Column("ID_MATERIE", sa.Integer(), nullable=True),
        sa.Column("ID_SALA", sa.Integer(), nullable=True),
        sa.Column("ID_GRUPA", sa.Integer(), nullable=False),
        sa.Column("ID_PERIOADA", sa.Integer(), nullable=False),
        sa.Column("TIP_ORA_MATERIE", sa.String(length=24), nullable=True),
        sa.Column("ORA_INCEPUT", sa.Time(), nullable=False),
        sa.Column("ORA_SFARSIT", sa.Time(), nullable=False),
        sa.Column("ZI_SAPTAMANA", sa.String(length=12), nullable=False),
        sa.Column("FRECVENTA", sa.String(length=4), nullable=True),
        sa.Column("SAPTAMANI", sa.String(length=80), nullable=True),
        sa.Column("SEMIGRUPA", sa.String(length=8), nullable=True),
        sa.Column("SURSA_PAGINA", sa.String(length=60), nullable=True),
        sa.Column("CONFIDENCE", sa.Double(), nullable=True),
        sa.Column("SURSA_BBOX", sa.String(length=40), nullable=True),
        sa.Column("CAMPURI_NESIGURE", sa.String(length=60), nullable=True),
        sa.ForeignKeyConstraint(
            ["ID_GRUPA"],
            ["GRUPA.ID_GRUPA"],
        ),
        sa.ForeignKeyConstraint(
            ["ID_MATERIE"],
            ["MATERIE.ID_MATERIE"],
        ),
        sa.ForeignKeyConstraint(
            ["ID_PERIOADA"],
            ["PERIOADA.ID_PERIOADA"],
        ),
        sa.ForeignKeyConstraint(
            ["ID_PROFESOR"],
            ["PROFESOR.ID_PROFESOR"],
        ),
        sa.ForeignKeyConstraint(
            ["ID_SALA"],
            ["SALA.ID_SALA"],
        ),
        sa.ForeignKeyConstraint(["ID_VERSIUNE"], ["VERSIUNE_ORAR.ID_VERSIUNE"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ID_ORA_ARHIVA"),
    )
    with op.batch_alter_table("ORA_ARHIVA", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ORA_ARHIVA_ID_GRUPA"), ["ID_GRUPA"], unique=False)
        batch_op.create_index(batch_op.f("ix_ORA_ARHIVA_ID_MATERIE"), ["ID_MATERIE"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ORA_ARHIVA_ID_PROFESOR"), ["ID_PROFESOR"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ORA_ARHIVA_ID_SALA"), ["ID_SALA"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ORA_ARHIVA_ID_VERSIUNE"), ["ID_VERSIUNE"], unique=False
        )

    op.create_table(
        "ORA_GRUPA_ARHIVA",
        sa.Column("ID_ORA_ARHIVA", sa.Integer(), nullable=False),
        sa.Column("ID_GRUPA", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["ID_GRUPA"], ["GRUPA.ID_GRUPA"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["ID_ORA_ARHIVA"], ["ORA_ARHIVA.ID_ORA_ARHIVA"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("ID_ORA_ARHIVA", "ID_GRUPA"),
    )
    # Autogenerate propunea si FLOAT -> Double pe ORA.CONFIDENCE: e doar denumirea noua din
    # SQLAlchemy pentru acelasi tip SQLite (REAL), nu o schimbare. Scoasa, ca sa nu
    # reconstruiasca tabela ORA degeaba.

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ORA_GRUPA_ARHIVA")
    with op.batch_alter_table("ORA_ARHIVA", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ORA_ARHIVA_ID_VERSIUNE"))
        batch_op.drop_index(batch_op.f("ix_ORA_ARHIVA_ID_SALA"))
        batch_op.drop_index(batch_op.f("ix_ORA_ARHIVA_ID_PROFESOR"))
        batch_op.drop_index(batch_op.f("ix_ORA_ARHIVA_ID_MATERIE"))
        batch_op.drop_index(batch_op.f("ix_ORA_ARHIVA_ID_GRUPA"))

    op.drop_table("ORA_ARHIVA")
    with op.batch_alter_table("VERSIUNE_ORAR", schema=None) as batch_op:
        batch_op.drop_index("ix_versiune_an_sem")

    op.drop_table("VERSIUNE_ORAR")
    # ### end Alembic commands ###
