"""sesizari si corectii manuale

  - SESIZARE: problemele semnalate din paginile de orar, pentru coada adminilor;
  - CORECTIE: ce schimba un admin in orar (o activitate adaugata, alt profesor, alta sala),
    tinut separat ca sa poata fi pus la loc dupa fiecare ingest;
  - ORA.ID_CORECTIE: activitatea adaugata sau modificata de o corectie.

Revision ID: 9fa0364012f9
Revises: 6c1f0a7d2e41
Create Date: 2026-09-30 11:30:47.445784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9fa0364012f9"
down_revision: Union[str, Sequence[str], None] = "6c1f0a7d2e41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "CORECTIE",
        sa.Column("ID_CORECTIE", sa.Integer(), nullable=False),
        sa.Column("CREAT_LA", sa.DateTime(), nullable=False),
        sa.Column("CREAT_DE", sa.String(length=120), nullable=False),
        sa.Column("FEL", sa.String(length=12), nullable=False),
        sa.Column("AN_UNIV", sa.String(length=12), nullable=False),
        sa.Column("SEMESTRU", sa.Integer(), nullable=False),
        sa.Column("GRUPA_SLUG", sa.String(length=180), nullable=False),
        sa.Column("ZI", sa.String(length=12), nullable=False),
        sa.Column("ORA_INCEPUT", sa.Time(), nullable=False),
        sa.Column("ORA_SFARSIT", sa.Time(), nullable=False),
        sa.Column("MATERIE", sa.String(length=160), nullable=True),
        sa.Column("TIP", sa.String(length=24), nullable=True),
        sa.Column("SEMIGRUPA", sa.String(length=8), nullable=True),
        sa.Column("FRECVENTA", sa.String(length=4), nullable=True),
        sa.Column("SAPTAMANI", sa.String(length=80), nullable=True),
        sa.Column("PROFESOR_VECHI", sa.String(length=120), nullable=True),
        sa.Column("SALA_VECHE", sa.String(length=80), nullable=True),
        sa.Column("PROFESOR", sa.String(length=120), nullable=True),
        sa.Column("SALA", sa.String(length=80), nullable=True),
        sa.Column("APLICATA", sa.Boolean(), server_default="1", nullable=False),
        sa.CheckConstraint("FEL IN ('adaugare','modificare')", name="ck_corectie_fel"),
        sa.PrimaryKeyConstraint("ID_CORECTIE"),
    )
    with op.batch_alter_table("CORECTIE", schema=None) as batch_op:
        batch_op.create_index("ix_corectie_an_sem", ["AN_UNIV", "SEMESTRU"], unique=False)

    op.create_table(
        "SESIZARE",
        sa.Column("ID_SESIZARE", sa.Integer(), nullable=False),
        sa.Column("CREAT_LA", sa.DateTime(), nullable=False),
        sa.Column("STARE", sa.String(length=10), server_default="noua", nullable=False),
        sa.Column("PAGINA", sa.String(length=200), nullable=False),
        sa.Column("ID_ORA", sa.Integer(), nullable=True),
        sa.Column("ACTIVITATE", sa.String(length=300), nullable=True),
        sa.Column("MESAJ", sa.Text(), nullable=False),
        sa.Column("ID_USER", sa.Integer(), nullable=True),
        sa.Column("CONTACT", sa.String(length=180), nullable=True),
        sa.Column("TRATATA_DE", sa.String(length=120), nullable=True),
        sa.Column("TRATATA_LA", sa.DateTime(), nullable=True),
        sa.Column("NOTA", sa.String(length=500), nullable=True),
        sa.CheckConstraint("STARE IN ('noua','rezolvata','respinsa')", name="ck_sesizare_stare"),
        sa.ForeignKeyConstraint(["ID_ORA"], ["ORA.ID_ORA"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["ID_USER"], ["USER.ID"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("ID_SESIZARE"),
    )
    with op.batch_alter_table("SESIZARE", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_SESIZARE_ID_ORA"), ["ID_ORA"], unique=False)
        batch_op.create_index(batch_op.f("ix_SESIZARE_ID_USER"), ["ID_USER"], unique=False)
        batch_op.create_index("ix_sesizare_stare", ["STARE", "CREAT_LA"], unique=False)

    # Fara `batch_alter_table` pe ORA: batch reconstruieste tabela (o copiaza si o sterge pe
    # cea veche), iar migrarile ruleaza cu `PRAGMA foreign_keys=ON` -- stergerea ar lua cu ea,
    # in cascada, toate legaturile ORA_GRUPA. SQLite stie sa adauge direct o coloana noua,
    # cu tot cu cheia ei straina, cat timp e NULL implicit.
    op.execute(
        'ALTER TABLE "ORA" ADD COLUMN "ID_CORECTIE" INTEGER '
        'REFERENCES "CORECTIE" ("ID_CORECTIE") ON DELETE SET NULL'
    )
    op.create_index("ix_ORA_ID_CORECTIE", "ORA", ["ID_CORECTIE"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # La fel ca la upgrade: fara reconstruirea tabelei. `DROP COLUMN` merge in SQLite >= 3.35
    # dupa ce dispare indexul; cheia straina pleaca odata cu coloana.
    op.drop_index("ix_ORA_ID_CORECTIE", table_name="ORA")
    op.execute('ALTER TABLE "ORA" DROP COLUMN "ID_CORECTIE"')

    with op.batch_alter_table("SESIZARE", schema=None) as batch_op:
        batch_op.drop_index("ix_sesizare_stare")
        batch_op.drop_index(batch_op.f("ix_SESIZARE_ID_USER"))
        batch_op.drop_index(batch_op.f("ix_SESIZARE_ID_ORA"))

    op.drop_table("SESIZARE")
    with op.batch_alter_table("CORECTIE", schema=None) as batch_op:
        batch_op.drop_index("ix_corectie_an_sem")

    op.drop_table("CORECTIE")
    # ### end Alembic commands ###
